const tweets = [
    {
        profile: "/images/myprofile.png",
        username: "Codenest",
        slug: "my-profile",
        email: "codenest6@gmail.com",
        time: 4,
        unit: "h",
        content: "Prepare for an exhilarating revelation! Codenest's Game Development Department is set to launch on March 16, 2024. Stay tuned for an immersive journey into the realm of gaming innovation! 🥳😀🎮",
        contentImage: null,
        likesNumber: 90,
        commentsNumber: 0,
        password: 'cdn23',
        comments: [],
        id: 0
    },
    {
        profile: "https://pbs.twimg.com/profile_images/1625196076587225096/ByHsg0RV_400x400.jpg",
        username: "Shawaal Nadeem",
        slug: "Shawaal-Nadeem",
        email: "shawaalnadeem63@gmail.com",
        time: 10,
        unit: "h",
        content: "Hunt your Goal like a Hungry Beast.🔥",
        contentImage: null,
        likesNumber: 100,
        commentsNumber: 0,
        password: 'shl123',
        comments: [],
        id: 1
    },
    {
        profile: "https://pbs.twimg.com/profile_images/1018746740424392704/WiiWn1u2_400x400.jpg",
        username: "Nancy Jewel",
        slug: "Nancy-Jewel",
        email: "nancyjewel@gmail.com",
        time: 10,
        unit: "h",
        content: "I feel someone likes me and he can't live without me.",
        contentImage: 'https://pbs.twimg.com/media/FlZVINsaUAY99BY?format=jpg&name=900x900',
        likesNumber: 100,
        commentsNumber: 0,
        password: 'njm123',
        comments: [],
        id: 2
    },
    {
        profile: "https://pbs.twimg.com/profile_images/1625196076587225096/ByHsg0RV_400x400.jpg",
        username: "Shawaal Nadeem",
        slug: "Shawaal-Nadeem",
        email: "shawaalnadeem63@gmail.com",
        time: 5,
        unit: "h",
        content: "In your smile, I see something more beautiful than the stars.✨",
        contentImage: null,
        likesNumber: 109,
        commentsNumber: 0,
        password: 'shl123',
        comments: [],
        id: 3
    },
    {
        profile: "https://pbs.twimg.com/profile_images/1385596677151674371/y-hZT-CJ_400x400.jpg",
        username: "Muhammad Ahsaan",
        slug: "Muhammad-Ahsaan",
        email: "muhammadahsaan@gmail.com",
        time: 5,
        unit: "h",
        content: "Koi kisi ka nahi sab waqti sahary hain, idhr civic nhi to sab apny begany hain.",
        contentImage: null,
        likesNumber: 122,
        commentsNumber: 0,
        password: 'mah123',
        comments: [],
        id: 4
    },
    {
        profile: "https://pbs.twimg.com/profile_images/1683325380441128960/yRsRRjGO_400x400.jpg",
        username: "Elon Musk",
        slug: "Elon-Musk",
        email: "elonmusk@gmail.com",
        time: 5,
        unit: "h",
        content: "Starship Super Heavy Booster",
        contentImage: "https://pbs.twimg.com/media/F3Bt7f9XEBE60qc?format=jpg&name=large",
        likesNumber: 109,
        commentsNumber: 0,
        password: 'elmX',
        comments: [],
        id: 5
    },
    {
        profile: "/images/myprofile.jpeg",
        username: "Codenest",
        slug: "my-profile",
        email: "codenest6@gmail.com",
        time: 1,
        unit: "h",
        content: "Believe in yourself and all that you are. Know that there is something inside you that is greater than any obstacle.",
        contentImage: null,
        likesNumber: 40,
        commentsNumber: 0,
        password: 'cdn23',
        comments: [],
        id: 6
    },
    {
        profile: "https://pbs.twimg.com/profile_images/1404378291599937536/b-r3SWlW_400x400.jpg",
        username: "ICC",
        slug: "ICC",
        email: "icc@gmail.com",
        time: 7,
        unit: "h",
        content: "Rohit Sharma has admitted that India's ODI team have concerns at the No.4 batting position.",
        contentImage: "https://pbs.twimg.com/media/F3N_NMeXAAAQEhd?format=jpg&name=large",
        likesNumber: 115,
        commentsNumber: 0,
        password: 'icMatch',
        comments: [],
        id: 7
    },
    {
        profile: "https://pbs.twimg.com/profile_images/1672219882904072196/-Lt_IrhL_400x400.jpg",
        username: "Andrew Tate",
        slug: "Andrew-Tate",
        email: "andrewtate@gmail.com",
        time: 1,
        unit: "h",
        content: "If you truly wanted money, you wouldnt be able to sleep until you fucking had it.",
        contentImage: null,
        likesNumber: 96,
        commentsNumber: 0,
        password: 'tBro',
        comments: [],
        id: 8
    },
    {
        profile: "https://pbs.twimg.com/profile_images/1417471791845478403/MzAWCfK7_400x400.jpg",
        username: "Rockstar Games",
        slug: "Rockstar-Games",
        email: "rockstargames@gmail.com",
        time: 30,
        unit: "m",
        content: "Meet demand for illicit arms head-on with 2X GTA$ and RP on Bunker Sell Missions, and more in GTA Online. Get 30% off a Bunker, and use the new Career Progress feature on PS5 and Xbox Series X|S to earn even more from the lucrative world of Gunrunning",
        contentImage: "https://pbs.twimg.com/media/F3QzOv-W0AA8m3q?format=jpg&name=large",
        likesNumber: 212,
        commentsNumber: 0,
        password: 'rockG',
        comments: [],
        id: 9
    },
    {
        profile: "https://pbs.twimg.com/profile_images/1308769664240160770/AfgzWVE7_400x400.jpg",
        username: "Joe Biden",
        slug: "Joe-Biden",
        email: "joebiden@gmail.com",
        time: 2,
        unit: "h",
        content: "Unemployment remains near record lows, a higher share of working-age Americans are working now than in 20 years, and real wages for the average American worker are growing and are higher than before the pandemic—with lower-wage workers seeing the largest gains.",
        contentImage: null,
        likesNumber: 704,
        commentsNumber: 0,
        password: 'jbUS',
        comments: [],
        id: 10
    }
   
]
export default tweets;